#!/bin/bash

export JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS:-"-javaagent:/home/testing/init/extras/elastic-apm-agent.jar"}
export BRIDGE_TRACING_ENABLED=${BRIDGE_TRACING_ENABLED:-"true"}
export ELASTIC_APM_SERVER_URLS=${ELASTIC_APM_SERVER_URLS:-"http://host.docker.internal:8200"}
export ELASTIC_APM_LOG_FORMAT_SOUT=${ELASTIC_APM_LOG_FORMAT_SOUT:-"JSON"}
export ELASTIC_APM_ENABLE_LOG_CORRELATION=${ELASTIC_APM_ENABLE_LOG_CORRELATION:-"true"}
export ELASTIC_APM_APPLICATION_PACKAGES=${ELASTIC_APM_APPLICATION_PACKAGES:-"com.testing"}
export ELASTIC_APM_CENTRAL_CONFIG=${ELASTIC_APM_CENTRAL_CONFIG:-"true"}
export ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-"testingservice"}
export ELASTIC_APM_LOG_LEVEL=${ELASTIC_APM_LOG_LEVEL:-"INFO"}
export ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED=${ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED:-"true"}
export ELASTIC_APM_PROFILING_INFERRED_SPANS_INCLUDED_CLASSES=${ELASTIC_APM_PROFILING_INFERRED_SPANS_INCLUDED_CLASSES:-"com.testing.*"}
export ELASTIC_APM_PROFILING_INFERRED_SPANS_EXCLUDED_CLASSES=${ELASTIC_APM_PROFILING_INFERRED_SPANS_EXCLUDED_CLASSES:-"(?-i)java.*, (?-i)javax.*, (?-i)sun.*, (?-i)com.sun.*, (?-i)jdk.*, (?-i)org.apache.tomcat.*, (?-i)org.apache.catalina.*, (?-i)org.apache.coyote.*, (?-i)org.eclipse.jetty.*, (?-i)org.springframework.*"}
export ELASTIC_APM_DISABLE_INSTRUMENTATIONS=${ELASTIC_APM_DISABLE_INSTRUMENTATIONS:-"experimental, jdbc, redis"}